/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author mukes
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    String adminName;
    String adminPass;
    public AdminPanel(String name, String pass) {
        this.adminName = name;
        this.adminPass = pass;
        initComponents();
        menu1.setBackground(Color.white);
        setSize(870, 546);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        menuBody = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userName_Add_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pass_add_user = new javax.swing.JTextField();
        asAdmin = new javax.swing.JRadioButton();
        asClerk = new javax.swing.JRadioButton();
        Add_admin_clerk_button = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        username_remove_user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pass_admin_remove = new javax.swing.JTextField();
        remove_user_admin = new javax.swing.JButton();
        removeAdmin = new javax.swing.JRadioButton();
        removeClerk = new javax.swing.JRadioButton();
        tab2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tab3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        id_add = new javax.swing.JTextField();
        variety_add = new javax.swing.JTextField();
        name_add = new javax.swing.JTextField();
        stock_add = new javax.swing.JTextField();
        unit_add = new javax.swing.JTextField();
        discount_add = new javax.swing.JTextField();
        product_add_button = new javax.swing.JButton();
        tab4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        id_remove = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        variety_remove = new javax.swing.JTextField();
        product_remove_button = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mukes\\Downloads\\admin.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("STORE BILLING SYSTEM");

        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(250, 250, 250)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(logout_button)
                                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(logout_button)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 90));

        menuBody.setBackground(new java.awt.Color(0, 204, 204));
        menuBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBodyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBodyMousePressed(evt);
            }
        });

        menu1.setBackground(new java.awt.Color(0, 204, 204));
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menu1MouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Users");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
                menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                                .addContainerGap(27, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );
        menu1Layout.setVerticalGroup(
                menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );

        menu3.setBackground(new java.awt.Color(0, 204, 204));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Add Product");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
                menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        menu3Layout.setVerticalGroup(
                menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        menu4.setBackground(new java.awt.Color(0, 204, 204));
        menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Remove Product");

        javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
        menu4.setLayout(menu4Layout);
        menu4Layout.setHorizontalGroup(
                menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        menu4Layout.setVerticalGroup(
                menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        menu2.setBackground(new java.awt.Color(0, 204, 204));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Stocks");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
                menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );
        menu2Layout.setVerticalGroup(
                menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout menuBodyLayout = new javax.swing.GroupLayout(menuBody);
        menuBody.setLayout(menuBodyLayout);
        menuBodyLayout.setHorizontalGroup(
                menuBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBodyLayout.createSequentialGroup()
                                .addGroup(menuBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(menu4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        menuBodyLayout.setVerticalGroup(
                menuBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuBodyLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(menuBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 570));

        jLabel7.setText("Enter Username    : ");

        userName_Add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_Add_userActionPerformed(evt);
            }
        });

        jLabel8.setText("Assign Password  : ");

        pass_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_add_userActionPerformed(evt);
            }
        });

        asAdmin.setText("As Admin");
        asAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asAdminActionPerformed(evt);
            }
        });
        buttonGroup1.add(asAdmin);buttonGroup1.add(asClerk);
        asClerk.setText("As Clerk");

        Add_admin_clerk_button.setText("Add");
        Add_admin_clerk_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_admin_clerk_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel11Layout.createSequentialGroup()
                                                                .addComponent(asAdmin)
                                                                .addGap(57, 57, 57)
                                                                .addComponent(asClerk))
                                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(userName_Add_user, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                                                .addComponent(pass_add_user))))
                                        .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addGap(222, 222, 222)
                                                .addComponent(Add_admin_clerk_button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userName_Add_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pass_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(asAdmin)
                                        .addComponent(asClerk))
                                .addGap(44, 44, 44)
                                .addComponent(Add_admin_clerk_button)
                                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add user", jPanel11);

        jLabel9.setText("Enter Username         : ");

        username_remove_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_remove_userActionPerformed(evt);
            }
        });

        jLabel10.setText("Enter your password  :   ");

        remove_user_admin.setText("Remove");
        remove_user_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_user_adminActionPerformed(evt);
            }
        });
        buttonGroup2.add(removeAdmin);buttonGroup2.add(removeClerk);
        removeAdmin.setText("Admin");

        removeClerk.setText("Clerk");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(remove_user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(pass_admin_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                                                .addComponent(username_remove_user))))
                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(removeAdmin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(removeClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(username_remove_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(pass_admin_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(removeAdmin)
                                        .addComponent(removeClerk))
                                .addGap(40, 40, 40)
                                .addComponent(remove_user_admin)
                                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Remove user", jPanel12);

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
                tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        tab1Layout.setVerticalGroup(
                tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(80, Short.MAX_VALUE))
        );

        tabs.addTab("tab1", tab1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "Id", "Variety", "Name", "Stock", "Price/Unit", "Discount(%)"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
                tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        tab2Layout.setVerticalGroup(
                tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabs.addTab("tab2", tab2);

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel11.setText("Enter the following details");

        jLabel12.setText("Product_ ID                    : ");

        jLabel13.setText("Product Variety              : ");

        jLabel15.setText("Product name                : ");

        jLabel16.setText("Stock available               : ");

        jLabel17.setText("Price per unit                  : ");

        jLabel18.setText("Discount  in %                : ");

        id_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_addActionPerformed(evt);
            }
        });

        variety_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variety_addActionPerformed(evt);
            }
        });

        name_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_addActionPerformed(evt);
            }
        });

        stock_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_addActionPerformed(evt);
            }
        });

        unit_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_addActionPerformed(evt);
            }
        });

        product_add_button.setText("Add");
        product_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
                tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab3Layout.createSequentialGroup()
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tab3Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(tab3Layout.createSequentialGroup()
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(id_add, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(tab3Layout.createSequentialGroup()
                                                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addGroup(tab3Layout.createSequentialGroup()
                                                                                        .addGap(49, 49, 49)
                                                                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(variety_add, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                                        .addComponent(name_add)
                                                                        .addComponent(stock_add)
                                                                        .addComponent(unit_add)
                                                                        .addComponent(discount_add)))))
                                        .addGroup(tab3Layout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(product_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(323, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
                tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(id_add, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(variety_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tab3Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                        .addComponent(name_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(stock_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(unit_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(discount_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addComponent(product_add_button)
                                .addContainerGap(99, Short.MAX_VALUE))
        );

        tabs.addTab("tab3", tab3);

        jLabel19.setText("Enter Product ID  : ");

        jLabel20.setText("Enter variety         : ");

        product_remove_button.setText("Remove");
        product_remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_remove_buttonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Remove product");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
                tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab4Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(product_remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(tab4Layout.createSequentialGroup()
                                                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                                        .addComponent(id_remove)
                                                        .addComponent(variety_remove))))
                                .addContainerGap(335, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
                tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(id_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(variety_remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jCheckBox1)
                                .addGap(29, 29, 29)
                                .addComponent(product_remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(195, Short.MAX_VALUE))
        );

        tabs.addTab("tab4", tab4);

        getContentPane().add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 700, 480));

        pack();
    }// </editor-fold>

    private void userName_Add_userActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pass_add_userActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String[] x = {"1","2"};
        Main.main(x);
        dispose();
    }

    private void asAdminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuBodyMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menuBodyMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        tabs.setSelectedIndex(3);
    }

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        tabs.setSelectedIndex(2);
    }

    private void menu1MouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu1.setForeground(Color.blue);
    }

    private void menu1MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu1.setBackground(Color.white);
        menu2.setBackground(new Color(0,204,204));
        menu3.setBackground(new Color(0,204,204));
        menu4.setBackground(new Color(0,204,204));
    }

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        tabs.setSelectedIndex(0);

    }

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        tabs.setSelectedIndex(1);
    }

    private void menu2MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu2.setBackground(Color.white);
        menu1.setBackground(new Color(0,204,204));
        menu3.setBackground(new Color(0,204,204));
        menu4.setBackground(new Color(0,204,204));
        JFrame f = this;
        try {
//            jTable1.setModel(new DefaultTableModel());
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billing", "root", "tiger");
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery("select * from stock;");
            while (rs.next()){
                String id = String.valueOf(rs.getString(1));
                String variety = String.valueOf(rs.getString(2));
                String name = String.valueOf(rs.getString(3));
                String  stock = String.valueOf(rs.getInt(4));
                String  price = String.valueOf(rs.getInt(5));
                String  discount = String.valueOf(rs.getInt(6));
                String[] data = {id, variety, name, stock, price, discount};
                dt.addRow(data);
            }
            con.close();
        }catch (Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(f,"Failed Connection");
        }
    }

    private void menu3MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu3.setBackground(Color.white);
        menu2.setBackground(new Color(0,204,204));
        menu1.setBackground(new Color(0,204,204));
        menu4.setBackground(new Color(0,204,204));

    }

    private void menu4MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu4.setBackground(Color.white);
        menu2.setBackground(new Color(0,204,204));
        menu3.setBackground(new Color(0,204,204));
        menu1.setBackground(new Color(0,204,204));
    }

    private void username_remove_userActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void remove_user_adminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame f = this;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billing", "root", "tiger");
            Statement smt = con.createStatement();
            ResultSet rs;
            String uname = username_remove_user.getText();
            String pass = pass_admin_remove.getText();
            System.out.println(uname +"  "+pass);
            if(uname.isEmpty() || pass.isEmpty()){
                JOptionPane.showMessageDialog(f, "Please enter Username & Password");
            }else{
                if(removeAdmin.isSelected() || removeClerk.isSelected()) {
                    if(removeAdmin.isSelected()) {
                        try {
                            rs = smt.executeQuery("select * from admins where username='" + uname + "'");
                            rs.next();
                            String name = rs.getString(1);
                            if (uname.equals(name) && pass.equals(adminPass)) {
                                int c = smt.executeUpdate("delete from admins where username ='" + uname + "'");
                                if (c > 0) {
                                    username_remove_user.setText("");
                                    pass_admin_remove.setText("");
                                    JOptionPane.showMessageDialog(f, "Removed Successfully");
                                } else {
                                    JOptionPane.showMessageDialog(f, "Something went wrong");
                                }
                            } else {
                                JOptionPane.showMessageDialog(f, "Username or Your password is incorrect");
                            }
                        }catch (Exception e){
                            JOptionPane.showMessageDialog(f, "User doesn't exists, try again");
                        }
                    }else {
                        try {
                            rs = smt.executeQuery("select * from clerk where username = '" + uname + "'");
                            System.out.println(adminName + "  " + adminPass);
                            rs.next();
                            String name = rs.getString(1);
                            if (uname.equals(name) && pass.equals(adminPass)) {
                                int c = smt.executeUpdate("delete from clerk where username ='" + uname + "'");
                                if (c > 0) {
                                    username_remove_user.setText("");
                                    pass_admin_remove.setText("");
                                    JOptionPane.showMessageDialog(f, "Removed Successfully");
                                } else {
                                    JOptionPane.showMessageDialog(f, "Something went wrong");
                                }
                            } else {
                                JOptionPane.showMessageDialog(f, "Username or Your password is incorrect");
                            }
                        }catch (Exception e){
                            JOptionPane.showMessageDialog(f, "User doesn't exists, try again");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(f, "Please select admin or clerk");
                }
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
//            e.printStackTrace();
            JOptionPane.showMessageDialog(f,"Failed Connection");
        }


    }

    private void unit_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void stock_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void name_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void variety_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void id_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void product_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame f = this;
        String id = null;
        String variety=null;
        String name=null;
        int stock = 0;
        int price  = 0;
        int discount = 0;
        try {
            id = String.valueOf(id_add.getText());
            variety = String.valueOf(variety_add.getText());
            name  = String.valueOf(name_add.getText());
            stock = Integer.valueOf(stock_add.getText());
            price = Integer.valueOf(unit_add.getText());
            discount = Integer.valueOf(discount_add.getText());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billing", "root", "tiger");
            Statement smt = con.createStatement();
            smt.executeUpdate("insert into stock values('"+id+"', '"+variety+"', '"+name+"', '"+stock+"', '"+price+"', '"+discount+"');");
            JOptionPane.showMessageDialog(f,"Added successfully");
            variety_add.setText("");
            id_add.setText("");
            name_add.setText("");
            stock_add.setText("");
            unit_add.setText("");
            discount_add.setText("");
        }catch (Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(f,"Invalid input. Check again");
        }
    }

    private void Add_admin_clerk_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame f = this;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","tiger");
            Statement smt = con.createStatement();
            ResultSet rs,rs1;
            if(!(asAdmin.isSelected() || asClerk.isSelected())){
                JOptionPane.showMessageDialog(f,"Please Select asadmin or asclerk");
            }else{
                if(asAdmin.isSelected()){
                    String uname = userName_Add_user.getText();
                    String pass = pass_add_user.getText();
                    if(uname.isEmpty() || pass.isEmpty()){
                        JOptionPane.showMessageDialog(f, "Please enter Username & Password");
                    }else{
                        int c = smt.executeUpdate("insert into admins values('"+uname+"', '"+pass+"');");
                        if(c>0){
                            userName_Add_user.setText("");
                            pass_add_user.setText("");
                            JOptionPane.showMessageDialog(f,"Added Successfully");
                        }else{
                            JOptionPane.showMessageDialog(f,"Something went wrong, try again");
                        }
                    }
                }else{
                    String uname = userName_Add_user.getText();
                    String pass = pass_add_user.getText();
                    System.out.println(uname +" "+ pass);
                    if(uname.isEmpty() || pass.isEmpty()){
                        JOptionPane.showMessageDialog(f, "Please enter Username & your Password");
                    }else{
                        int c = smt.executeUpdate("insert into clerk values('"+uname+"', '"+pass+"');");
                        if(c>0){
                            userName_Add_user.setText("");
                            pass_add_user.setText("");
                            JOptionPane.showMessageDialog(f,"Added Successfully");
                        }else{
                            JOptionPane.showMessageDialog(f,"Something went wrong, try again");
                        }
                    }
                }
            }
            con.close();
        }catch (Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(f,"Failed Connection");
        }
    }

    private void product_remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFrame f = this;
        try {
            String id = String.valueOf(id_remove.getText());
            String variety = String.valueOf(variety_remove.getText());
            if(jCheckBox1.isSelected()){
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billing","root","tiger");
            Statement smt = con.createStatement();
            int x = smt.executeUpdate("delete from stock where product_id = '"+id+"' and product_variety = '"+variety+"';");
            if (x > 0){
                JOptionPane.showMessageDialog(f,"Removed product : "+id);
                id_remove.setText("");
                variety_remove.setText("");
            }else {
                throw new ArithmeticException("Wrong input");
            }
            }else {
                JOptionPane.showMessageDialog(f,"Please select remove product");
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(f,"Invalid input, check again.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel(args[0], args[1]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Add_admin_clerk_button;
    private javax.swing.JRadioButton asAdmin;
    private javax.swing.JRadioButton asClerk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField discount_add;
    private javax.swing.JTextField id_add;
    private javax.swing.JTextField id_remove;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JPanel menuBody;
    private javax.swing.JTextField name_add;
    private javax.swing.JTextField pass_add_user;
    private javax.swing.JTextField pass_admin_remove;
    private javax.swing.JButton product_add_button;
    private javax.swing.JButton product_remove_button;
    private javax.swing.JRadioButton removeAdmin;
    private javax.swing.JRadioButton removeClerk;
    private javax.swing.JButton remove_user_admin;
    private javax.swing.JTextField stock_add;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField unit_add;
    private javax.swing.JTextField userName_Add_user;
    private javax.swing.JTextField username_remove_user;
    private javax.swing.JTextField variety_add;
    private javax.swing.JTextField variety_remove;
    // End of variables declaration
}
